INSERT INTO it_park_user (name, age) VALUES ('Marsel', 23);
INSERT INTO it_park_user ( name, age) VALUES ( 'Ruslan', 25);
INSERT INTO it_park_user ( name, age) VALUES ( 'Alina', 18);
INSERT INTO it_park_user ( name, age) VALUES ( 'Regina', 19);
INSERT INTO it_park_user ( name, age) VALUES ( 'Rustam', 33);
INSERT INTO it_park_user ( name, age) VALUES ( 'Ilmir', 27);
INSERT INTO it_park_user ( name, age) VALUES ( 'Aydar', 27);
INSERT INTO it_park_user ( name, age) VALUES ( 'Misha', 20);
INSERT INTO it_park_user ( name, age) VALUES ( 'Ilyas', 20);
INSERT INTO it_park_user ( name, age) VALUES ( 'Lena', 30);